[package]
name = "travel_expense"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
